services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db

  task-manager:
    build: .
    image: kshitijpatil508/task-manager:latest
    container_name: task-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb_container:27017/taskmanager?authSource=admin
      - ADMIN_USER=admin
      - ADMIN_PASS=Admin@1234
    depends_on:
      - mongodb_container

volumes:
  mongodb_data:
    driver: local
